version: '3.8'
services:

  postgres:
    build:
      context: ./postgres_service
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "5432:5432"
    
  jupyter_lab:
    build: 
      context: ./jupyter-lab
      dockerfile: Dockerfile
    ports:
       - 8888:8888
    networks:
      - my_network
    volumes:
      - jupyter_volume:/app/my_data
      
    depends_on:
      - postgres

  r_studio:
    build:
      context: ./r_service
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    networks:
      - my_network
    depends_on:
      - postgres
    environment:
      - USER=ds_fmat
      - PASSWORD=rstudio
    volumes:
      - r_volume:/home/ds_fmat

networks:
  my_network:
    driver: bridge
volumes:
  jupyter_volume:
    driver: local
    driver_opts:  
      type: none
      o: bind
      device: ./jupyter-lab/files/
  r_volume:
    driver: local
    driver_opts:  
      type: none
      o: bind
      device: ./r_service/files/